valor = input('Digite algo: ')

print('O tipo primitivo desse valor é', type(valor))
print('Só tem espaços?', valor.isspace())
print('É um número?', valor.isnumeric())
print('É alfabético?', valor.isalpha())
print('É um alfanúmerico?', valor.isalnum())
print('Está em maiúsculas?', valor.isupper())
print('Está em minúsculos?', valor.islower())
print('Está capitalizada?', valor.istitle())
